<a href="https://colab.research.google.com/github/09-ashish/DSA-CaseStudies/blob/main/Activity(numpy%2Cpandas).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

**Activity-numpy**


In [2]:
arr1=np.arange(10,50)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [3]:
arr1=arr1.reshape(4,10)
arr1

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [4]:
print(arr1[:,-1])

[19 29 39 49]


In [5]:
arr2=np.full((3,3),5)
arr3=np.arange(1,10).reshape(3,3)
arr2,arr3

(array([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

In [6]:
sum=arr2+arr3
sum


array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [7]:
mul=arr2*arr3
mul


array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [8]:
mul.T

array([[ 5, 20, 35],
       [10, 25, 40],
       [15, 30, 45]])

In [9]:
arr4=np.random.randint(10,100,15)
arr4

array([25, 17, 37, 29, 45, 21, 93, 36, 42, 98, 58, 78, 40, 76, 49])

In [10]:
arr4=np.where(arr4>50,-1,arr4)
arr4

array([25, 17, 37, 29, 45, 21, -1, 36, 42, -1, -1, -1, 40, -1, 49])

In [11]:
count=(arr4==-1).sum()
count

np.int64(5)

In [12]:
arr5=np.random.uniform(0,1,size=(5,4))
arr5

array([[0.66732108, 0.15328231, 0.1647191 , 0.67431858],
       [0.80501912, 0.98631467, 0.19462505, 0.06505441],
       [0.59703006, 0.56798999, 0.57557383, 0.75756312],
       [0.34892975, 0.81256862, 0.21148411, 0.29611572],
       [0.5282893 , 0.98231566, 0.89568295, 0.04932455]])

In [13]:
row_sum=arr5.sum(axis=1)
print(row_sum)
index=row_sum.argmax()
index

[1.65964107 2.05101324 2.49815701 1.6690982  2.45561247]


np.int64(2)

In [14]:
row_min=arr5.min(axis=1,keepdims=True)
row_max=arr5.max(axis=1,keepdims=True)

Normalized= (arr5 - row_min)/(row_max - row_min)

Normalized

array([[0.98657005, 0.        , 0.02195007, 1.        ],
       [0.80320919, 1.        , 0.14064499, 0.        ],
       [0.15318663, 0.        , 0.04000478, 1.        ],
       [0.22866276, 1.        , 0.        , 0.14079819],
       [0.51336476, 1.        , 0.9071452 , 0.        ]])

In [15]:
arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
np.unique(arr)

array([1, 3, 5, 7, 9])

In [16]:
import numpy as np

arr = np.arange(12).reshape(3,4)

a = arr.reshape(2,6)
b = a.flatten()
c = b.reshape(4,3)

print(c)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [17]:
a = np.array([[1,2],
              [3,4]])

a = np.vstack((a,[5,6]))

a = np.hstack((a,
               np.array([[7],
                         [8],
                         [9]])))

print(a)

[[1 2 7]
 [3 4 8]
 [5 6 9]]


In [18]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

arr = np.concatenate((a,b,c))

mat = arr.reshape(3,3)

diag = np.diag(mat)

print(mat)
print(diag)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]


In [19]:
import numpy as np

arr = np.arange(1,21)

result = arr[(arr % 3 == 0) | (arr % 5 == 0)]

print(result)
print("Count =", len(result))

[ 3  5  6  9 10 12 15 18 20]
Count = 9


pandas

In [20]:
import pandas as pd
import numpy as np

df = pd.read_csv("titanic_dataset.csv")

In [21]:
print(df.head(10))

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54

In [22]:
print(df.isnull().sum())

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64


In [23]:
print(df.groupby("Sex")["Survived"].mean() * 100)

Sex
female    74.203822
male      18.890815
Name: Survived, dtype: float64


In [24]:
print("Average:", df["Age"].mean())
print("Median:", df["Age"].median())
print("Std:", df["Age"].std())

Average: 29.69911764705882
Median: 28.0
Std: 14.526497332334044


In [25]:
print(df["Pclass"].value_counts())

Pclass
3    491
1    216
2    184
Name: count, dtype: int64


In [26]:
print(df[(df["Sex"]=="female") &
         (df["Age"]<18) &
         (df["Survived"]==1)])

     PassengerId  Survived  Pclass  \
9             10         1       2   
10            11         1       3   
22            23         1       3   
39            40         1       3   
43            44         1       2   
58            59         1       2   
68            69         1       3   
84            85         1       2   
156          157         1       3   
172          173         1       3   
184          185         1       3   
208          209         1       3   
233          234         1       3   
237          238         1       2   
307          308         1       1   
329          330         1       1   
381          382         1       3   
389          390         1       2   
435          436         1       1   
446          447         1       2   
448          449         1       3   
469          470         1       3   
479          480         1       3   
504          505         1       1   
530          531         1       2   
535         

In [27]:
df["Age"] = df["Age"].fillna(df["Age"].median())

In [28]:
def age_group(age):
    if age < 18:
        return "Child"
    elif age <= 60:
        return "Adult"
    else:
        return "Senior"

df["age_group"] = df["Age"].apply(age_group)

In [29]:
print(df.nlargest(5, "Fare"))

     PassengerId  Survived  Pclass                                Name  \
258          259         1       1                    Ward, Miss. Anna   
679          680         1       1  Cardeza, Mr. Thomas Drake Martinez   
737          738         1       1              Lesurer, Mr. Gustave J   
27            28         0       1      Fortune, Mr. Charles Alexander   
88            89         1       1          Fortune, Miss. Mabel Helen   

        Sex   Age  SibSp  Parch    Ticket      Fare        Cabin Embarked  \
258  female  35.0      0      0  PC 17755  512.3292          NaN        C   
679    male  36.0      0      1  PC 17755  512.3292  B51 B53 B55        C   
737    male  35.0      0      0  PC 17755  512.3292         B101        C   
27     male  19.0      3      2     19950  263.0000  C23 C25 C27        S   
88   female  23.0      3      2     19950  263.0000  C23 C25 C27        S   

    age_group  
258     Adult  
679     Adult  
737     Adult  
27      Adult  
88      Adul

In [30]:
print(df.groupby(["Pclass","Sex"])["Fare"].mean())

Pclass  Sex   
1       female    106.125798
        male       67.226127
2       female     21.970121
        male       19.741782
3       female     16.118810
        male       12.661633
Name: Fare, dtype: float64


In [31]:
df.rename(columns={
    "Sex":"gender",
    "Fare":"ticket_fare"
}, inplace=True)

In [32]:
print(df.groupby(["Pclass","Survived"]).size())

Pclass  Survived
1       0            80
        1           136
2       0            97
        1            87
3       0           372
        1           119
dtype: int64
